[package]
name = "rhai-autodocs"
version = "0.1.5"
edition = "2021"
authors = ["Lucas Tabis"]
description = "Custom documentation generator for the Rhai scripting language"
homepage = "https://github.com/ltabis/rhai-autodocs"
repository = "https://github.com/ltabis/rhai-autodocs"
readme = "README.md"
license = "MIT"
include = ["/src/**/*", "/Cargo.toml", "/README.md", "LICENSE*"]
keywords = [
    "scripting",
    "scripting-engine",
    "scripting-language",
    "documentation",
]
categories = ["development-tools"]

[dependencies]
rhai = { version = "1.11.0", features = ["metadata"] }
serde_json = "1.0.89"
serde = { version = "1.0.147", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3.0"

[[example]]
name = "basic"
path = "examples/basic/main.rs"
