[package]
name = "rhai-autodocs"
version = "0.1.0"
edition = "2021"


[dependencies]
rhai = { version = "1.11.0", features = ["metadata"] }
serde_json = "1.0.89"
serde = { version = "1.0.147", features = ["derive"] }
